import Mathlib

/-!
# NRRF775 — The natural form selector on the Uniface

The reading being formalised (beat `2026-08-26-0934-et`, integrating the selected occurrence
`2026-08-25-central-note`):

> Action in flight: a *natural form selector* on the Uniface.  An **undetermined string** is carried
> to a **relational determination**; the determination yields a **unique unitary path partition**;
> **halt and continuation are traces**, not determinations.  Sense persistence and the ellipse are
> already live upstream.  **TRUE is not issued.**

Every clause becomes a theorem, and nothing is assumed beyond ordinary Mathlib.

* **§1 Undetermined string → relational determination.**  A string on the Uniface is a map
  `ℕ → Option S`: `none` at a site is an *undetermined* slot, not an error.  A *relational
  determination* is a site-indexed relation `R : ℕ → S → Prop`, and it is `Rigid` when each site
  admits exactly one related symbol.  For a rigid relation the natural form `sel R hR` exists and is
  the *unique* total determination (`naturalForm_exists_unique`), it refines every string compatible
  with `R` (`naturalForm_refines`), and any two determinations of the same relation coincide
  (`determination_unique`).  The last statement is *sense persistence*: the natural form depends on
  the relation alone, never on how much of the string happened to be filled in already
  (`naturalForm_indep_of_partial_input`).  The honest converse
  (`exists_two_determinations_of_not_rigid`) shows rigidity is exactly what is load-bearing: where
  the relation admits two symbols at an undetermined site, determination genuinely branches.

* **§2 Unique unitary path partition.**  A *unitary* symbol is a bijection `e : Equiv.Perm α`.  Its
  path relation `PathRel e x y ↔ ∃ k : ℤ, (e ^ k) x = y` is an equivalence
  (`pathRel_equivalence`); its classes cover (`iUnion_path`) and are pairwise equal-or-disjoint
  (`path_eq_or_disjoint`) and step-invariant (`path_apply_mem`).  Uniqueness is
  `pathSetoid_finest` / `path_partition_unique`: *the* path partition is the unique equivalence that
  is both closed under the unitary step and generated by it.  So the selector does not choose a
  partition; the determined unitary symbol already has exactly one.

* **§3 Halt and continuation as traces.**  A partial step `step : σ → Option σ` has a run
  `run step x`, whose trace set `traceSet step x` is downward closed (`traceSet_downwardClosed`) and
  is either all of `ℕ` (continuation) or an initial segment `Iio N` with `N` the halt time
  (`traceSet_eq_univ_or_Iio`).  Halting and continuing are exclusive and exhaustive
  (`halts_or_continues`, `not_halts_and_continues`); the halt time is the least trace bound
  (`haltTime_spec`, `haltTime_min`).  Both readings are therefore *traces of the same run*.  And the
  trace is not part of the determination: `exists_same_form_different_halting` exhibits one relation
  whose natural form is shared by a halting run and a continuing one.

* **§4 TRUE is not issued.**  `exists_rigid_with_no_true_symbol` gives a rigid relation whose natural
  form is total and unique while no site ever carries the symbol `true`: determination is complete
  without any verdict being emitted.  `naturalForm_indep_of_valuation` says the same structurally —
  the selector is a function of the relation, so no valuation of symbols can influence it.

* **§5 The Uniface itself.**  `Uniface` bundles a rigid relational determination; `Uniface.form` is
  its natural form and `Uniface.form_unique` its uniqueness.  `nrrf775_answer` collects the clauses.
-/

namespace NRRF775

/-! ## §1 Undetermined strings and relational determination -/

/-- A string on the Uniface: `none` marks an *undetermined* site. -/
abbrev Str (S : Type*) := ℕ → Option S

variable {S : Type*}

/-- A string is determined when no site is left open. -/
def Determined (s : Str S) : Prop := ∀ n, (s n).isSome

/-- `t` refines `s`: everything `s` already fixes, `t` keeps. -/
def Refines (t s : Str S) : Prop := ∀ n a, s n = some a → t n = some a

/-- A relational determination: which symbols the relation admits at each site. -/
def Constraint (S : Type*) := ℕ → S → Prop

/-- The relation determines each site: exactly one admissible symbol. -/
def Rigid (R : Constraint S) : Prop := ∀ n, ∃! a, R n a

/-- A string is compatible with a relation when everything it fixes is admissible. -/
def Compat (s : Str S) (R : Constraint S) : Prop := ∀ n a, s n = some a → R n a

/-- **The natural form selector.**  For a rigid relational determination, the symbol at each site
is the unique one the relation admits there. -/
noncomputable def sel (R : Constraint S) (hR : Rigid R) : ℕ → S := fun n => (hR n).choose

theorem sel_admissible (R : Constraint S) (hR : Rigid R) (n : ℕ) : R n (sel R hR n) :=
  (hR n).choose_spec.1

theorem sel_eq_of_admissible {R : Constraint S} (hR : Rigid R) {n : ℕ} {a : S} (h : R n a) :
    a = sel R hR n :=
  (hR n).choose_spec.2 a h

/-- Two determinations of the same relation are the same: the natural form is unique. -/
theorem determination_unique {R : Constraint S} (hR : Rigid R) {t u : ℕ → S}
    (ht : ∀ n, R n (t n)) (hu : ∀ n, R n (u n)) : t = u := by
  funext n
  rw [sel_eq_of_admissible hR (ht n), sel_eq_of_admissible hR (hu n)]

/-- **Undetermined string → relational determination.**  A rigid relation has one and only one
total determination. -/
theorem naturalForm_exists_unique {R : Constraint S} (hR : Rigid R) :
    ∃! t : ℕ → S, ∀ n, R n (t n) :=
  ⟨sel R hR, sel_admissible R hR, fun _ ht => determination_unique hR ht (sel_admissible R hR)⟩

/-- The natural form refines every string compatible with the relation: nothing already fixed is
overwritten. -/
theorem naturalForm_refines {R : Constraint S} (hR : Rigid R) {s : Str S} (hs : Compat s R) :
    Refines (fun n => some (sel R hR n)) s := by
  intro n a ha
  rw [sel_eq_of_admissible hR (hs n a ha)]

/-- The natural form is determined. -/
theorem naturalForm_determined {R : Constraint S} (hR : Rigid R) :
    Determined (fun n => some (sel R hR n)) := fun _ => rfl

/-- **Sense persistence.**  Two runs of the selector started from *different* partially determined
strings on the same relation produce the same natural form: the sense carried by the relation
persists through any amount of prior determination. -/
theorem naturalForm_indep_of_partial_input {R : Constraint S} (hR : Rigid R) {s s' : Str S}
    (hs : Compat s R) (hs' : Compat s' R) :
    Refines (fun n => some (sel R hR n)) s ∧ Refines (fun n => some (sel R hR n)) s' ∧
      ∀ t : ℕ → S, (∀ n, R n (t n)) → t = sel R hR :=
  ⟨naturalForm_refines hR hs, naturalForm_refines hR hs',
    fun _ ht => determination_unique hR ht (sel_admissible R hR)⟩

/-- Honest converse: where the relation is not rigid at an undetermined site, determination really
does branch — two admissible determinations refine the same string. -/
theorem exists_two_determinations_of_not_rigid {R : Constraint S} {n : ℕ} {a b : S}
    (hne : a ≠ b) (ha : R n a) (hb : R n b) (htot : ∀ m, ∃ c, R m c)
    {s : Str S} (hs : Compat s R) (hopen : s n = none) :
    ∃ t u : ℕ → S, (∀ m, R m (t m)) ∧ (∀ m, R m (u m)) ∧
      Refines (fun m => some (t m)) s ∧ Refines (fun m => some (u m)) s ∧ t ≠ u := by
  classical
  set fill : ℕ → S := fun m => (s m).getD ((htot m).choose) with hfill
  have hfill_adm : ∀ m, R m (fill m) := by
    intro m
    rcases hsm : s m with _ | c
    · simpa [hfill, hsm] using (htot m).choose_spec
    · simpa [hfill, hsm] using hs m c hsm
  have hfill_ref : ∀ m c, s m = some c → fill m = c := by
    intro m c hc; simp [hfill, hc]
  refine ⟨fun m => if m = n then a else fill m, fun m => if m = n then b else fill m,
          ?_, ?_, ?_, ?_, ?_⟩
  · intro m; by_cases h : m = n
    · subst h; simpa using ha
    · simpa [h] using hfill_adm m
  · intro m; by_cases h : m = n
    · subst h; simpa using hb
    · simpa [h] using hfill_adm m
  · intro m c hc
    by_cases h : m = n
    · subst h; rw [hopen] at hc; exact absurd hc (by simp)
    · simp [h, hfill_ref m c hc]
  · intro m c hc
    by_cases h : m = n
    · subst h; rw [hopen] at hc; exact absurd hc (by simp)
    · simp [h, hfill_ref m c hc]
  · intro hcontra
    exact hne (by simpa using congrFun hcontra n)

/-! ## §2 The unique unitary path partition -/

variable {α : Type*}

/-- The path relation of a unitary symbol: `y` lies on the path of `x` when some integer power of
the step carries `x` to `y`. -/
def PathRel (e : Equiv.Perm α) (x y : α) : Prop := ∃ k : ℤ, (e ^ k) x = y

theorem pathRel_refl (e : Equiv.Perm α) (x : α) : PathRel e x x := ⟨0, by simp⟩

theorem pathRel_symm {e : Equiv.Perm α} {x y : α} (h : PathRel e x y) : PathRel e y x := by
  obtain ⟨k, hk⟩ := h
  exact ⟨-k, by rw [← hk]; simp [← Equiv.Perm.mul_apply]⟩

theorem pathRel_trans {e : Equiv.Perm α} {x y z : α} (h₁ : PathRel e x y) (h₂ : PathRel e y z) :
    PathRel e x z := by
  obtain ⟨k, hk⟩ := h₁
  obtain ⟨l, hl⟩ := h₂
  exact ⟨l + k, by rw [zpow_add, Equiv.Perm.mul_apply, hk, hl]⟩

theorem pathRel_equivalence (e : Equiv.Perm α) : Equivalence (PathRel e) :=
  ⟨pathRel_refl e, pathRel_symm, pathRel_trans⟩

/-- The path partition of a unitary symbol, as a setoid. -/
def pathSetoid (e : Equiv.Perm α) : Setoid α := ⟨PathRel e, pathRel_equivalence e⟩

/-- The path of `x` under the unitary step. -/
def path (e : Equiv.Perm α) (x : α) : Set α := {y | PathRel e x y}

theorem mem_path_self (e : Equiv.Perm α) (x : α) : x ∈ path e x := pathRel_refl e x

/-- The paths cover: every datum lies on a path. -/
theorem iUnion_path (e : Equiv.Perm α) : (⋃ x : α, path e x) = Set.univ := by
  ext y
  simp only [Set.mem_iUnion, Set.mem_univ, iff_true]
  exact ⟨y, mem_path_self e y⟩

/-- The step keeps a datum on its own path. -/
theorem path_apply_mem (e : Equiv.Perm α) (x : α) : e x ∈ path e x := ⟨1, by simp⟩

/-- Paths are equal or disjoint: they really are a partition. -/
theorem path_eq_or_disjoint (e : Equiv.Perm α) (x y : α) :
    path e x = path e y ∨ Disjoint (path e x) (path e y) := by
  by_cases h : ∃ z, z ∈ path e x ∧ z ∈ path e y
  · obtain ⟨z, hzx, hzy⟩ := h
    left
    ext w
    constructor
    · exact fun hw => pathRel_trans (pathRel_trans hzy (pathRel_symm hzx)) hw
    · exact fun hw => pathRel_trans (pathRel_trans hzx (pathRel_symm hzy)) hw
  · right
    rw [Set.disjoint_left]
    intro z hzx hzy
    exact h ⟨z, hzx, hzy⟩

/-- Every integer power stays inside any step-closed equivalence. -/
theorem rel_zpow_of_step_closed {r : α → α → Prop} (hr : Equivalence r) {e : Equiv.Perm α}
    (hstep : ∀ x, r x (e x)) (k : ℤ) (x : α) : r x ((e ^ k) x) := by
  induction k using Int.induction_on with
  | zero => simpa using hr.refl x
  | succ i ih =>
      have hx : ((e ^ ((i : ℤ) + 1)) x) = e ((e ^ (i : ℤ)) x) := by
        rw [add_comm, zpow_add, zpow_one, Equiv.Perm.mul_apply]
      rw [hx]
      exact hr.trans ih (hstep _)
  | pred i ih =>
      have hinv : ∀ y : α, r y (e⁻¹ y) := by
        intro y
        exact hr.symm (by simpa using hstep (e⁻¹ y))
      have hx : ((e ^ (-(i : ℤ) - 1)) x) = e⁻¹ ((e ^ (-(i : ℤ))) x) := by
        rw [sub_eq_neg_add, zpow_add, zpow_neg, zpow_one, Equiv.Perm.mul_apply]
      rw [hx]
      exact hr.trans ih (hinv _)

/-- **The path partition is the finest step-closed partition.**  Any equivalence closed under the
unitary step contains the path relation. -/
theorem pathSetoid_finest {e : Equiv.Perm α} {r : α → α → Prop} (hr : Equivalence r)
    (hstep : ∀ x, r x (e x)) {x y : α} (h : PathRel e x y) : r x y := by
  obtain ⟨k, hk⟩ := h
  exact hk ▸ rel_zpow_of_step_closed hr hstep k x

/-- **Unique unitary path partition.**  An equivalence that is closed under the unitary step and
generated by it *is* the path relation — so the determined unitary symbol carries exactly one
partition into paths. -/
theorem path_partition_unique {e : Equiv.Perm α} {r : α → α → Prop} (hr : Equivalence r)
    (hstep : ∀ x, r x (e x)) (hgen : ∀ x y, r x y → PathRel e x y) : r = PathRel e := by
  funext x y
  exact propext ⟨hgen x y, pathSetoid_finest hr hstep⟩

/-! ## §3 Halt and continuation as traces -/

variable {σ : Type*}

/-- The run of a partial step: `none` records that the run has stopped. -/
def run (step : σ → Option σ) (x : σ) : ℕ → Option σ
  | 0 => some x
  | n + 1 => (run step x n).bind step

@[simp] theorem run_zero (step : σ → Option σ) (x : σ) : run step x 0 = some x := rfl

@[simp] theorem run_succ (step : σ → Option σ) (x : σ) (n : ℕ) :
    run step x (n + 1) = (run step x n).bind step := rfl

/-- The run halts: some stage is empty. -/
def Halts (step : σ → Option σ) (x : σ) : Prop := ∃ n, run step x n = none

/-- The run continues: every stage carries a state. -/
def Continues (step : σ → Option σ) (x : σ) : Prop := ∀ n, (run step x n).isSome

theorem run_none_succ {step : σ → Option σ} {x : σ} {n : ℕ} (h : run step x n = none) :
    run step x (n + 1) = none := by simp [h]

theorem run_none_of_le {step : σ → Option σ} {x : σ} {m n : ℕ} (hmn : m ≤ n)
    (h : run step x m = none) : run step x n = none := by
  induction n with
  | zero => exact (Nat.le_zero.mp hmn) ▸ h
  | succ k ih =>
      rcases Nat.lt_or_ge m (k + 1) with hlt | hge
      · exact run_none_succ (ih (by omega))
      · have : m = k + 1 := le_antisymm hmn hge
        exact this ▸ h

theorem not_halts_and_continues {step : σ → Option σ} {x : σ} :
    ¬(Halts step x ∧ Continues step x) := by
  rintro ⟨⟨n, hn⟩, hc⟩
  have := hc n
  rw [hn] at this
  exact absurd this (by simp)

theorem halts_or_continues (step : σ → Option σ) (x : σ) : Halts step x ∨ Continues step x := by
  by_cases h : Halts step x
  · exact Or.inl h
  · right
    intro n
    rcases hrun : run step x n with _ | y
    · exact absurd ⟨n, hrun⟩ h
    · simp

/-- The trace set of a run: the stages that carry a state. -/
def traceSet (step : σ → Option σ) (x : σ) : Set ℕ := {n | (run step x n).isSome}

theorem zero_mem_traceSet (step : σ → Option σ) (x : σ) : 0 ∈ traceSet step x := by
  simp [traceSet]

/-- Traces are downward closed: a stage is reached only if all earlier stages were. -/
theorem traceSet_downwardClosed {step : σ → Option σ} {x : σ} {m n : ℕ} (hmn : m ≤ n)
    (hn : n ∈ traceSet step x) : m ∈ traceSet step x := by
  by_contra hm
  have hm' : run step x m = none := by
    simpa [traceSet, Option.isSome_iff_exists, Option.eq_none_iff_forall_ne_some] using hm
  have := run_none_of_le hmn hm'
  rw [traceSet, Set.mem_setOf_eq, this] at hn
  exact absurd hn (by simp)

/-- The halt time: the first empty stage. -/
noncomputable def haltTime {step : σ → Option σ} {x : σ} (h : Halts step x) : ℕ := Nat.find h

theorem haltTime_spec {step : σ → Option σ} {x : σ} (h : Halts step x) :
    run step x (haltTime h) = none := Nat.find_spec h

theorem haltTime_min {step : σ → Option σ} {x : σ} (h : Halts step x) {n : ℕ}
    (hn : n < haltTime h) : n ∈ traceSet step x := by
  have := Nat.find_min h hn
  rcases hrun : run step x n with _ | y
  · exact absurd hrun this
  · simp [traceSet, hrun]

theorem haltTime_pos {step : σ → Option σ} {x : σ} (h : Halts step x) : 0 < haltTime h := by
  rcases Nat.eq_zero_or_pos (haltTime h) with h0 | hpos
  · have := haltTime_spec h
    rw [h0] at this
    exact absurd this (by simp)
  · exact hpos

/-- **Halt and continuation are the two shapes of a trace.**  The trace set of any run is either all
of `ℕ` — the continuing reading — or the initial segment below the halt time. -/
theorem traceSet_eq_univ_or_Iio (step : σ → Option σ) (x : σ) :
    traceSet step x = Set.univ ∨ ∃ N : ℕ, 0 < N ∧ traceSet step x = Set.Iio N := by
  rcases halts_or_continues step x with h | h
  · right
    refine ⟨haltTime h, haltTime_pos h, ?_⟩
    ext n
    constructor
    · intro hn
      by_contra hge
      have hge' : haltTime h ≤ n := by simpa using hge
      have := run_none_of_le hge' (haltTime_spec h)
      rw [traceSet, Set.mem_setOf_eq, this] at hn
      exact absurd hn (by simp)
    · exact fun hn => haltTime_min h hn
  · left
    ext n
    simpa [traceSet] using h n

/-- A rigid relational determination on the two-symbol alphabet that admits only `false`. -/
def falseOnly : Constraint Bool := fun _ a => a = false

theorem falseOnly_rigid : Rigid falseOnly := fun _ => ⟨false, rfl, fun _ hy => hy⟩

theorem sel_falseOnly (n : ℕ) : sel falseOnly falseOnly_rigid n = false :=
  (sel_eq_of_admissible falseOnly_rigid (n := n) (a := false) rfl).symm

/-- The trace is not part of the determination: one and the same relational determination is shared
by a halting run and a continuing one. -/
theorem exists_same_form_different_halting :
    ∃ (R : Constraint Bool) (hR : Rigid R) (s₁ s₂ : ℕ → Option ℕ),
      Halts s₁ 0 ∧ Continues s₂ 0 ∧ (∀ n, sel R hR n = false) := by
  refine ⟨falseOnly, falseOnly_rigid, fun _ => none, fun k => some (k + 1), ⟨1, by simp⟩, ?_,
    sel_falseOnly⟩
  intro n
  induction n with
  | zero => simp
  | succ k ih =>
      rcases hrun : run (fun k => some (k + 1)) 0 k with _ | y
      · rw [hrun] at ih; exact absurd ih (by simp)
      · simp [hrun]

/-! ## §4 TRUE is not issued -/

/-- **TRUE is not issued.**  There is a rigid relational determination whose natural form is total
and unique, and at which no site ever carries `true`: determination is complete without a verdict
being emitted. -/
theorem exists_rigid_with_no_true_symbol :
    ∃ (R : Constraint Bool) (hR : Rigid R), (∀ n, R n (sel R hR n)) ∧ (∀ n, sel R hR n ≠ true) :=
  ⟨falseOnly, falseOnly_rigid, sel_admissible _ _, fun n => by rw [sel_falseOnly n]; simp⟩

/-- The selector is a function of the relation alone, so no valuation of the symbols can influence
the natural form. -/
theorem naturalForm_indep_of_valuation {R R' : Constraint S} (hR : Rigid R) (hR' : Rigid R')
    (h : ∀ n a, R n a ↔ R' n a) : sel R hR = sel R' hR' := by
  have hR'' : ∀ n, R n (sel R' hR' n) := fun n => (h n _).2 (sel_admissible R' hR' n)
  exact (determination_unique hR (sel_admissible R hR) hR'').symm ▸ rfl

/-! ## §5 The Uniface -/

/-- A **Uniface**: a relational determination on strings over an alphabet, rigid enough to select. -/
structure Uniface (S : Type*) where
  /-- Which symbols the relation admits at each site. -/
  rel : Constraint S
  /-- Each site is determined by the relation. -/
  rigid : Rigid rel

namespace Uniface

variable (U : Uniface S)

/-- The natural form selected on the Uniface. -/
noncomputable def form : ℕ → S := sel U.rel U.rigid

theorem form_admissible (n : ℕ) : U.rel n (U.form n) := sel_admissible _ _ n

/-- The natural form is the unique determination on the Uniface. -/
theorem form_unique : ∃! t : ℕ → S, ∀ n, U.rel n (t n) := naturalForm_exists_unique U.rigid

/-- The natural form refines any partially determined string of the Uniface. -/
theorem form_refines {s : Str S} (hs : Compat s U.rel) : Refines (fun n => some (U.form n)) s :=
  naturalForm_refines U.rigid hs

end Uniface

/-- The five clauses of the beat, in one statement:
determination is unique; the natural form refines the undetermined string; a unitary symbol carries
exactly one path partition; halt and continuation are the two shapes of a trace; and TRUE is never
issued. -/
theorem nrrf775_answer :
    (∀ {S : Type} (U : Uniface S), ∃! t : ℕ → S, ∀ n, U.rel n (t n)) ∧
    (∀ {S : Type} (U : Uniface S) (s : Str S), Compat s U.rel →
      Refines (fun n => some (U.form n)) s) ∧
    (∀ {α : Type} (e : Equiv.Perm α) (r : α → α → Prop), Equivalence r → (∀ x, r x (e x)) →
      (∀ x y, r x y → PathRel e x y) → r = PathRel e) ∧
    (∀ {σ : Type} (step : σ → Option σ) (x : σ),
      traceSet step x = Set.univ ∨ ∃ N : ℕ, 0 < N ∧ traceSet step x = Set.Iio N) ∧
    (∃ (R : Constraint Bool) (hR : Rigid R), ∀ n, sel R hR n ≠ true) :=
  ⟨fun U => U.form_unique, fun U _ hs => U.form_refines hs,
   fun _ _ hr hstep hgen => path_partition_unique hr hstep hgen,
   fun step x => traceSet_eq_univ_or_Iio step x,
   by
     obtain ⟨R, hR, _, hno⟩ := exists_rigid_with_no_true_symbol
     exact ⟨R, hR, hno⟩⟩

end NRRF775
