import Slearn.ClosedTopologicalTranslation

/-
Closure-generated Slearn spatial field.

This module replaces the earlier reconstruction that gated a predeclared UI
topology.  There is no canonical core/brain/value/belief/WHY/goal graph here.
The only formal input is an interaction field.  A spatial presentation is
admitted exactly as a projection of that field, and a change of zoom is
admitted only through a re-reading with a preserved bridge.

The result is deliberately structural.  It does not prove a particular browser
layout, physical law, empirical learning result, independence of a receipt, or
uniqueness of an educational UI.
-/

universe u v w x

namespace Slearn

namespace UIHairOfClosure

/-- A relative position is a reading of one relation, not a new translation operator. -/
inductive RelativePosition
  | natural
  | dual
  | obstructed
  deriving DecidableEq, Repr

/-- The presentation selected by a closure operation. -/
inductive Lens
  | expanded
  | contracted
  | returned
  deriving DecidableEq, Repr

/-- The only visible roles generated by a closure relation. -/
inductive SpatialRole
  | presentation
  | context
  | translation
  | closure
  | world
  | successor
  deriving DecidableEq, Repr

/-- OPEN is a positive result when an interaction lacks a bridge or return. -/
inductive MapVerdict
  | open
  | path
  | returned
  | dual
  | obstruction
  deriving DecidableEq, Repr

/--
The learner-side relation field.  `Trace` is deliberately neutral: one trace
can be read as a WHY path, a topic re-reading, a definition/language change,
or a lesson/project path.  None of those readings is separately hard-coded as
a UI layer.
-/
structure InteractionField (Presentation : Type u) (Trace : Type v)
    (Receipt : Type w) where
  source : Trace → Presentation
  context : Trace → Presentation
  target : Trace → Presentation
  world : Trace → Presentation
  translated : Trace → Prop
  hasContext : Trace → Prop
  hasWorld : Trace → Prop
  redefined : Trace → Prop
  preserved : Trace → Prop
  attempted : Trace → Prop
  returnReceipt : Trace → Receipt → Prop
  successor : Receipt → Presentation
  position : Trace → RelativePosition

namespace InteractionField

variable {Presentation : Type u} {Trace : Type v} {Receipt : Type w}

/-- A relation exists before it can appear in any spatial presentation. -/
def Admitted (F : InteractionField Presentation Trace Receipt) (t : Trace) : Prop :=
  F.translated t

/--
A bridge is the explicit continuation data missing from a frozen level: the
relation is re-read and a relation that persists through that re-reading is
recorded.  Its words are not enough; both predicates belong to the trace.
-/
def Bridge (F : InteractionField Presentation Trace Receipt) (t : Trace) : Prop :=
  F.Admitted t ∧ F.redefined t ∧ F.preserved t

/-- A return additionally requires an attempted trace and a supplied receipt. -/
def Returned (F : InteractionField Presentation Trace Receipt) (t : Trace) : Prop :=
  F.Bridge t ∧ F.attempted t ∧ ∃ r, F.returnReceipt t r

/-- A generated spatial occurrence always retains its source trace. -/
structure SpatialOccurrence (F : InteractionField Presentation Trace Receipt) where
  role : SpatialRole
  trace : Trace
  admissible : F.Admitted trace
  visible : Presentation
  presents :
    match role with
    | .presentation => visible = F.source trace
    | .context => visible = F.context trace
    | .translation => visible = F.target trace
    | .closure => visible = F.target trace
    | .world => visible = F.world trace
    | .successor => ∃ r, F.returnReceipt trace r ∧ visible = F.successor r

/-- The spatial field is a predicate, not a stored list of nodes or coordinates. -/
def SpatialClosure (F : InteractionField Presentation Trace Receipt)
    (lens : Lens) : SpatialOccurrence F → Prop
  | occurrence =>
      match lens, occurrence.role with
      | .expanded, .presentation => True
      | .expanded, .context => F.hasContext occurrence.trace
      | .expanded, .translation => True
      | .expanded, .closure => True
      | .expanded, .world => F.Bridge occurrence.trace ∧ F.hasWorld occurrence.trace
      | .contracted, .closure => F.Bridge occurrence.trace
      | .returned, .presentation => True
      | .returned, .context => F.hasContext occurrence.trace
      | .returned, .translation => True
      | .returned, .closure => True
      | .returned, .world => F.Bridge occurrence.trace ∧ F.hasWorld occurrence.trace
      | .returned, .successor => F.Returned occurrence.trace
      | _, _ => False

/-- The closure transitions admitted by a selected trace. -/
inductive LensTransition (F : InteractionField Presentation Trace Receipt)
    (t : Trace) : Lens → Lens → Prop
  | contract (h : F.Bridge t) : LensTransition F t .expanded .contracted
  | reopen (h : F.Bridge t) : LensTransition F t .contracted .expanded
  | returned (h : F.Returned t) : LensTransition F t .expanded .returned

/--
The only editable axes of an open Slearn trace.  These are closure data
requirements, not an independently chosen collection of form fields.
-/
inductive ClosureSeed
  | perspective
  | context
  | whyRelation
  | direction
  | reReading
  | preservedBridge
  | relativePosition
  | world
  | source
  | lesson
  | attempt
  | receipt
  | successor
  deriving DecidableEq, Repr

/-- Learning material is attached to an admitted trace, never a free sidebar. -/
inductive LearningRole
  | source
  | lesson
  | project
  deriving DecidableEq, Repr

/-- A source, lesson, or project in the generated learning field. -/
structure LearningOccurrence (F : InteractionField Presentation Trace Receipt)
    (Material : Type x) where
  role : LearningRole
  trace : Trace
  admissible : F.Admitted trace
  material : Material

namespace LearningOccurrence

variable {F : InteractionField Presentation Trace Receipt} {Material : Type x}

/-- Projects require a recorded attempt; sources and lessons require the trace. -/
def visible (L : LearningOccurrence F Material) : Prop :=
  match L.role with
  | .source | .lesson => True
  | .project => F.attempted L.trace

/-- Every visible learning material retains an admitted closure trace. -/
theorem visible_has_admitted_trace (L : LearningOccurrence F Material)
    (_h : L.visible) : F.Admitted L.trace :=
  L.admissible

/-- A visible project cannot be manufactured without an attempt. -/
theorem visible_project_requires_attempt (L : LearningOccurrence F Material)
    (hrole : L.role = .project) (hvisible : L.visible) : F.attempted L.trace := by
  cases L with
  | mk role trace admissible material =>
      cases role <;> simp at hrole
      simpa [visible] using hvisible

end LearningOccurrence

/--
The complete formal scene contract.  A renderer may choose a physical medium,
but it receives no independent points, connections, or actions: points are
exactly spatial closure occurrences and actions are exactly lens transitions.
-/
structure ClosureMachineScene (F : InteractionField Presentation Trace Receipt)
    (lens : Lens) where
  point : SpatialOccurrence F → Prop
  connection : SpatialOccurrence F → SpatialOccurrence F → Prop
  learning : ∀ {Material : Type x}, LearningOccurrence F Material → Prop
  operation : Trace → Lens → Lens → Prop
  seed : ClosureSeed → Prop

/-- The unique scene contract directly generated by the closure field. -/
def generatedScene (F : InteractionField Presentation Trace Receipt)
    (lens : Lens) : ClosureMachineScene F lens where
  point := F.SpatialClosure lens
  connection := fun left right => F.SpatialClosure lens left ∧ F.SpatialClosure lens right
  learning := fun learning => learning.visible
  operation := LensTransition F
  seed := fun _ => True

namespace ClosureMachineScene

variable (F : InteractionField Presentation Trace Receipt) (lens : Lens)

/-- The generated scene contains every and only closure-admitted points. -/
theorem point_iff_spatialClosure (o : SpatialOccurrence F) :
    (F.generatedScene lens).point o ↔
      F.SpatialClosure lens o := by
  rfl

/-- A rendered connection cannot smuggle in a non-closure endpoint. -/
theorem connection_requires_closure
    {left right : SpatialOccurrence F}
    (h : (F.generatedScene lens).connection left right) :
    F.SpatialClosure lens left ∧ F.SpatialClosure lens right :=
  h

/-- A visible source, lesson, or project is also closure-derived. -/
theorem learning_requires_admitted_trace
    {Material : Type x} {learning : LearningOccurrence F Material}
    (h : (F.generatedScene lens).learning learning) : F.Admitted learning.trace :=
  learning.visible_has_admitted_trace h

/-- A rendered operation is a closure transition, not a camera action. -/
theorem operation_is_lens_transition
    {t : Trace} {origin target : Lens}
    (h : (F.generatedScene lens).operation t origin target) :
    LensTransition F t origin target :=
  h

/-- Editable seeds are exhausted by the declared closure axes. -/
theorem no_independent_seed (s : ClosureSeed) :
    (F.generatedScene lens).seed s :=
  True.intro

end ClosureMachineScene

/-- An expanded presentation has no independently admitted spatial role. -/
theorem expanded_role_is_relation
    (F : InteractionField Presentation Trace Receipt)
    {o : SpatialOccurrence F}
    (h : F.SpatialClosure .expanded o) :
    o.role = .presentation ∨ o.role = .context ∨ o.role = .translation ∨
      o.role = .closure ∨ o.role = .world := by
  cases o with
  | mk role trace admissible visible presents =>
      cases role <;> simp [SpatialClosure] at h ⊢

/-- A context/value presentation is visible only when the trace supplies it. -/
theorem context_requires_context
    (F : InteractionField Presentation Trace Receipt)
    {o : SpatialOccurrence F}
    (h : F.SpatialClosure .expanded o)
    (hrole : o.role = .context) : F.hasContext o.trace := by
  cases o with
  | mk role trace admissible visible presents =>
      cases role <;> simp at hrole
      simpa [SpatialClosure] using h

/-- A world/universe orientation is a bridged global continuation, never free scenery. -/
theorem world_requires_bridge_and_global_relation
    (F : InteractionField Presentation Trace Receipt)
    {o : SpatialOccurrence F}
    (h : F.SpatialClosure .expanded o)
    (hrole : o.role = .world) : F.Bridge o.trace ∧ F.hasWorld o.trace := by
  cases o with
  | mk role trace admissible visible presents =>
      cases role <;> simp at hrole
      simpa [SpatialClosure] using h

/-- A contracted occurrence cannot be shown without the trace's bridge. -/
theorem contracted_requires_bridge
    (F : InteractionField Presentation Trace Receipt)
    {o : SpatialOccurrence F}
    (h : F.SpatialClosure .contracted o) : F.Bridge o.trace := by
  cases o with
  | mk role trace admissible visible presents =>
      cases role <;> simp [SpatialClosure] at h
      exact h

/-- No unbridged trace is silently available in a contracted projection. -/
theorem no_bridge_no_contracted_occurrence
    (F : InteractionField Presentation Trace Receipt) {t : Trace}
    (h : ¬ F.Bridge t) :
    ∀ {o : SpatialOccurrence F}, o.trace = t → ¬ F.SpatialClosure .contracted o := by
  intro o htrace hshown
  apply h
  rw [← htrace]
  exact F.contracted_requires_bridge hshown

/-- A successor presentation can be displayed only from a returned trace. -/
theorem successor_requires_return
    (F : InteractionField Presentation Trace Receipt)
    {o : SpatialOccurrence F}
    (h : F.SpatialClosure .returned o)
    (hrole : o.role = .successor) : F.Returned o.trace := by
  cases o with
  | mk role trace admissible visible presents =>
      cases role <;> simp at hrole
      simpa [SpatialClosure] using h

/-- A return is a continuation, not literal identity of source and successor. -/
structure ReturnContinuation (F : InteractionField Presentation Trace Receipt)
    (t : Trace) where
  receipt : Receipt
  hasReceipt : F.returnReceipt t receipt
  successorChanged : F.successor receipt ≠ F.source t

/-- A continuation with changed successor never asserts literal return. -/
theorem continuation_not_literal_return
    {F : InteractionField Presentation Trace Receipt} {t : Trace}
    (C : ReturnContinuation F t) : F.successor C.receipt ≠ F.source t :=
  C.successorChanged

/-- A topic re-reading can contract only through its explicit bridge. -/
theorem transition_to_contracted_requires_bridge
    {F : InteractionField Presentation Trace Receipt} {t : Trace}
    {origin : Lens} (h : LensTransition F t origin .contracted) : F.Bridge t := by
  cases h with
  | contract hb => exact hb

/-- A return projection is unavailable until bridge, attempt, and receipt exist. -/
theorem transition_to_returned_requires_return
    {F : InteractionField Presentation Trace Receipt} {t : Trace}
    {origin : Lens} (h : LensTransition F t origin .returned) : F.Returned t := by
  cases h with
  | returned hr => exact hr

/-- The visible verdict is derived from one selected trace. -/
noncomputable def verdict (F : InteractionField Presentation Trace Receipt) (t : Trace) : MapVerdict := by
  classical
  exact match F.position t with
    | .dual => .dual
    | .obstructed => .obstruction
    | .natural => if F.Returned t then .returned else if F.Bridge t then .path else .open

/-- A trace without a bridge remains OPEN in its natural position. -/
theorem no_bridge_is_open
    (F : InteractionField Presentation Trace Receipt) {t : Trace}
    (hposition : F.position t = .natural) (hbridge : ¬ F.Bridge t) :
    F.verdict t = .open := by
  classical
  have hreturned : ¬ F.Returned t := by
    intro hr
    exact hbridge hr.1
  simp [verdict, hposition, hreturned, hbridge]

/-- A dual trace remains one relation in a dual reading rather than another operator. -/
theorem dual_is_relative_position
    (F : InteractionField Presentation Trace Receipt) {t : Trace}
    (hposition : F.position t = .dual) : F.verdict t = .dual := by
  classical
  simp [verdict, hposition]

/-- An obstruction is recorded rather than replaced by a manufactured path. -/
theorem obstruction_is_recorded
    (F : InteractionField Presentation Trace Receipt) {t : Trace}
    (hposition : F.position t = .obstructed) : F.verdict t = .obstruction := by
  classical
  simp [verdict, hposition]

/--
A bridge between presentation levels is injective and relation-reflecting.
This is the minimal extra certificate required to distinguish a translation
chain from a succession of frozen local assertions.
-/
structure LevelBridge (Earlier : Type u) (Later : Type v)
    (earlierRelated : Earlier → Earlier → Prop)
    (laterRelated : Later → Later → Prop) where
  forward : Earlier → Later
  injective : Function.Injective forward
  reflects : ∀ {a b}, laterRelated (forward a) (forward b) → earlierRelated a b

namespace LevelBridge

variable {Earlier : Type u} {Later : Type v} {Final : Type w}
variable {earlierRelated : Earlier → Earlier → Prop}
  {laterRelated : Later → Later → Prop} {finalRelated : Final → Final → Prop}

/-- Two level bridges compose, retaining both injectivity and reflection. -/
def compose
    (B : LevelBridge Earlier Later earlierRelated laterRelated)
    (C : LevelBridge Later Final laterRelated finalRelated) :
    LevelBridge Earlier Final earlierRelated finalRelated where
  forward := C.forward ∘ B.forward
  injective := by
    intro a b hab
    apply B.injective
    apply C.injective
    exact hab
  reflects := by
    intro a b hab
    exact B.reflects (C.reflects hab)

end LevelBridge

/-- A round step is frozen only when no presentation is genuinely moved. -/
def Frozen {State : Type u} (round : State → State) : Prop :=
  ∀ state, round state = state

/-- Translation requires relational return and at least one actual movement. -/
def Translating {State : Type u} (related : State → State → Prop)
    (round : State → State) : Prop :=
  (∀ state, related (round state) state) ∧ ∃ state, round state ≠ state

/-- Frozen and translating are exclusive. -/
theorem frozen_not_translating
    {State : Type u} {related : State → State → Prop} {round : State → State}
    (hfrozen : Frozen round) : ¬ Translating related round := by
  intro htranslating
  obtain ⟨state, hmoved⟩ := htranslating.2
  exact hmoved (hfrozen state)

end InteractionField

/-- A small abstract fibre used only to state the non-global-hair obstruction. -/
inductive HairDirection
  | zero
  | east
  | north
  | west
  | south
  deriving DecidableEq, Repr

/-- A stated quarter-turn transport on the fibre, with no physical interpretation. -/
def quarterTurn : HairDirection → HairDirection
  | .zero => .zero
  | .east => .north
  | .north => .west
  | .west => .south
  | .south => .east

/-- Only the zero direction is fixed by this nontrivial transport. -/
theorem quarterTurn_fixed_is_zero {d : HairDirection}
    (h : quarterTurn d = d) : d = .zero := by
  cases d <;> simp [quarterTurn] at h ⊢

/-- A globally coherent hair is a direction fixed by the supplied return transport. -/
def GloballyCoherentHair (d : HairDirection) : Prop :=
  quarterTurn d = d

/-- Under the quarter-turn transport, global coherence is informative zero. -/
theorem globallyCoherentHair_is_zero {d : HairDirection}
    (h : GloballyCoherentHair d) : d = .zero :=
  quarterTurn_fixed_is_zero h

end UIHairOfClosure

end Slearn

#print axioms Slearn.UIHairOfClosure.InteractionField.contracted_requires_bridge
#print axioms Slearn.UIHairOfClosure.InteractionField.no_bridge_no_contracted_occurrence
#print axioms Slearn.UIHairOfClosure.InteractionField.context_requires_context
#print axioms Slearn.UIHairOfClosure.InteractionField.world_requires_bridge_and_global_relation
#print axioms Slearn.UIHairOfClosure.InteractionField.successor_requires_return
#print axioms Slearn.UIHairOfClosure.InteractionField.ClosureMachineScene.point_iff_spatialClosure
#print axioms Slearn.UIHairOfClosure.InteractionField.ClosureMachineScene.connection_requires_closure
#print axioms Slearn.UIHairOfClosure.InteractionField.ClosureMachineScene.learning_requires_admitted_trace
#print axioms Slearn.UIHairOfClosure.InteractionField.ClosureMachineScene.operation_is_lens_transition
#print axioms Slearn.UIHairOfClosure.InteractionField.transition_to_contracted_requires_bridge
#print axioms Slearn.UIHairOfClosure.InteractionField.transition_to_returned_requires_return
#print axioms Slearn.UIHairOfClosure.InteractionField.frozen_not_translating
#print axioms Slearn.UIHairOfClosure.quarterTurn_fixed_is_zero
#print axioms Slearn.UIHairOfClosure.globallyCoherentHair_is_zero
