import Mathlib
import Slearn.NRRF764ConsciousCulturalMoralitySuperNetwork

/-!
# NRRF766 — The public interface is fully interactive; the field is collective action, immutable by
closure

The reading being formalised:

> The network itself, through its digital public interface, is therefore fully interactive.
> "Interactive" means: on site, I can — and others — continuously evolve toward a shared
> architecture.  It consists of a field, not of quantity: quality, but collective action, with
> autonomous ai, me and others.  Immutable by closure.

This module continues `NRRF764ConsciousCulturalMoralitySuperNetwork` — its `Network` (the shared
interactive field of culture, morality and consciousness) is reused rather than restated — and
formalises the five claims of the new reading.

## §1  The digital public interface is fully interactive

A `Site` is a network together with what each participant *can do on site*: an admissible action on
the shared field.  `Site.run` runs a finite trace of on-site actions, `run_admissible` and
`run_shared` say that no trace ever leaves the shared field.  Full interactivity is
`Site.onSite_eq_traces`: the monoid of everything the interface can do is exactly the monoid of
finite traces of participants' interactions — the interface has no action of its own beyond the
interactions, and every combination of interactions is available on it.

## §2  Continuously evolving toward a shared architecture

Each participant contributes to the architecture over time (`contrib p n`), monotonically.  The
`shared` architecture is the union of all contributions: `contrib_subset_shared` places every
participant's trajectory inside it and `shared_least` makes it the least such — it is the limit
they evolve toward, not an extra thing imposed on them.  Because the interface is *public*
(`Public`: whatever is in the shared architecture reaches every participant in finite time),
`converges_to_shared` says each participant's own limit *is* the shared architecture: one
architecture, reached from every seat on the site.

## §3  A field of quality, not quantity — collective action

`interField t = t ×ˢ t` is the field of interactions a group of participants presents.
`IsQuantitative` says a valuation of groups depends only on how many members they have;
`interField_not_quantitative` shows the field is not of that kind — two groups of the same size
present different fields.  `interField_collective` is collective action: the field of a group
strictly exceeds the union of the fields of its members, and `card_interField` measures the excess
(`card ^ 2`, against `card` many members).  `interField_not_additive` states the same failure of
separability directly.

## §4  Autonomous ai, me and others

`Party` is the participants of the site: `me`, `other i`, and `ai i` (three distinct kinds:
`Party.me_ne_ai`, `Party.other_ne_ai`).  `Autonomous s p` says `p`'s
action is not generated by all the other participants' actions together — nobody else, in any
combination, can do what `p` does.  On the toggle site (`toggleSite`), `toggle_autonomous` shows
*every* participant is autonomous in this sense, in particular each ai; `toggle_collective` shows
that nevertheless the participants acting together reach every state of the field: autonomy of the
parts and collective action of the whole are not in tension.

## §5  Immutable by closure

A `Clo` is a closure operator on a complete lattice.  `Clo.immutable`: adding anything already
admitted by the closure changes the closure not at all; `Clo.immutable_trajectory`: a whole
trajectory of such additions leaves it unchanged; `Clo.closed_fixed` / `Clo.cl_idem`: what is
closed is a fixed point.  `sharedArchitecture_immutable` applies this to §2 — once the shared
architecture is closed, the continuing evolution of the site cannot alter it.

`nrrf766_answer` collects the reading in one theorem, and `nrrf766_answer_party` instantiates it at
an actual site of me, one other and one ai.
-/

namespace NRRF766

open Function NRRF764

universe u v w

/-! ## §1  The digital public interface is fully interactive -/

/-- A **site**: the digital public interface of a network.  Besides the shared field itself (the
`net`), it records what each participant *can do on site* — an action on readings of the field that
is admissible, i.e. that never carries the field outside itself. -/
structure Site (P : Type u) (V : Type v) where
  /-- The shared interactive field the site is an interface to. -/
  net : Network P V
  /-- What a participant can do on site. -/
  act : P → V → V
  /-- Every on-site action is an admissible reinterpretation of the field. -/
  act_admissible : ∀ p {x y}, net.admits x y → net.admits (act p x) (act p y)

namespace Site

variable {P : Type u} {V : Type v} (s : Site P V)

/-- A **trace**: a finite sequence of on-site interactions, run in order. -/
def run : List P → V → V
  | [], x => x
  | p :: t, x => run t (s.act p x)

@[simp] theorem run_nil (x : V) : s.run [] x = x := rfl

@[simp] theorem run_cons (p : P) (t : List P) (x : V) :
    s.run (p :: t) x = s.run t (s.act p x) := rfl

theorem run_append (t t' : List P) (x : V) :
    s.run (t ++ t') x = s.run t' (s.run t x) := by
  induction t generalizing x with
  | nil => rfl
  | cons p t ih => simp [ih]

/-- **Interaction never leaves the shared field.**  Whatever is done on site, admissible readings
stay admissible. -/
theorem run_admissible (t : List P) {x y : V} (h : s.net.admits x y) :
    s.net.admits (s.run t x) (s.run t y) := by
  induction t generalizing x y with
  | nil => exact h
  | cons p t ih => exact ih (s.act_admissible p h)

/-- The site is public: after any trace of interactions, any two participants' readings remain
readings of one shared field. -/
theorem run_shared (t : List P) (p q : P) :
    s.net.admits (s.run t (s.net.read p)) (s.run t (s.net.read q)) :=
  s.run_admissible t (s.net.shared p q)

/-- The endomorphism of the field a trace of interactions performs. -/
def runEnd (t : List P) : Function.End V := s.run t

@[simp] theorem runEnd_apply (t : List P) (x : V) : s.runEnd t x = s.run t x := rfl

theorem runEnd_append (t t' : List P) : s.runEnd (t ++ t') = s.runEnd t' * s.runEnd t := by
  funext x; simpa using s.run_append t t' x

/-- Everything the interface can do: the monoid generated by the participants' interactions. -/
def onSite : Submonoid (Function.End V) := Submonoid.closure (Set.range s.act)

/-- The traces of interactions, as a submonoid of the endomorphisms of the field. -/
def traces : Submonoid (Function.End V) where
  carrier := {f | ∃ t : List P, s.runEnd t = f}
  one_mem' := ⟨[], rfl⟩
  mul_mem' := by
    rintro f g ⟨t, rfl⟩ ⟨t', rfl⟩
    exact ⟨t' ++ t, s.runEnd_append t' t⟩

@[simp] theorem mem_traces {f : Function.End V} : f ∈ s.traces ↔ ∃ t : List P, s.runEnd t = f :=
  Iff.rfl

/-- **The interface is fully interactive.**  What the interface can do is exactly what the
participants can do through it: every combination of interactions is available on site, and the
site performs nothing that is not such a combination. -/
theorem onSite_eq_traces : s.onSite = s.traces := by
  apply le_antisymm
  · rw [onSite, Submonoid.closure_le]
    rintro f ⟨p, rfl⟩
    exact ⟨[p], rfl⟩
  · rintro f ⟨t, rfl⟩
    induction t with
    | nil =>
        have h1 : s.runEnd [] = (1 : Function.End V) := by funext x; rfl
        rw [h1]
        exact (s.onSite).one_mem
    | cons p t ih =>
        have hp : (s.act p : Function.End V) ∈ s.onSite :=
          Submonoid.subset_closure ⟨p, rfl⟩
        have : s.runEnd (p :: t) = s.runEnd t * s.runEnd [p] := by
          simpa using s.runEnd_append [p] t
        rw [this]
        exact (s.onSite).mul_mem ih (by simpa [runEnd, run] using hp)

/-- Everything the interface does is done by some finite trace of interactions on site. -/
theorem exists_trace_of_mem_onSite {f : Function.End V} (hf : f ∈ s.onSite) :
    ∃ t : List P, s.run t = f := by
  rw [onSite_eq_traces] at hf
  obtain ⟨t, ht⟩ := hf
  exact ⟨t, ht⟩

end Site

/-! ## §2  Continuously evolving toward a shared architecture -/

section Architecture

variable {P : Type u} {A : Type v}

/-- The **shared architecture** the site evolves toward: everything any participant has contributed
at any time. -/
def sharedArch (contrib : P → ℕ → Set A) : Set A := ⋃ p, ⋃ n, contrib p n

theorem contrib_subset_sharedArch (contrib : P → ℕ → Set A) (p : P) (n : ℕ) :
    contrib p n ⊆ sharedArch contrib := by
  intro a ha
  exact Set.mem_iUnion.2 ⟨p, Set.mem_iUnion.2 ⟨n, ha⟩⟩

/-- The shared architecture is the *least* thing containing every participant's evolution: it is
what they converge toward, not something imposed on top of them. -/
theorem sharedArch_least {contrib : P → ℕ → Set A} {B : Set A}
    (h : ∀ p n, contrib p n ⊆ B) : sharedArch contrib ⊆ B := by
  intro a ha
  obtain ⟨p, hp⟩ := Set.mem_iUnion.1 ha
  obtain ⟨n, hn⟩ := Set.mem_iUnion.1 hp
  exact h p n hn

/-- A participant's own limit: everything they ever come to hold. -/
def limitOf (contrib : P → ℕ → Set A) (p : P) : Set A := ⋃ n, contrib p n

theorem limitOf_subset_sharedArch (contrib : P → ℕ → Set A) (p : P) :
    limitOf contrib p ⊆ sharedArch contrib := by
  intro a ha
  obtain ⟨n, hn⟩ := Set.mem_iUnion.1 ha
  exact contrib_subset_sharedArch contrib p n hn

/-- The interface is **public**: whatever belongs to the shared architecture reaches every
participant in finite time. -/
def Public (contrib : P → ℕ → Set A) : Prop :=
  ∀ p, ∀ a ∈ sharedArch contrib, ∃ n, a ∈ contrib p n

/-- **Continuously evolved toward a shared architecture.**  On a public interface, every
participant's own limit is the one shared architecture: everyone, from their own seat on the site,
evolves toward the same thing. -/
theorem converges_to_sharedArch {contrib : P → ℕ → Set A} (h : Public contrib) (p : P) :
    limitOf contrib p = sharedArch contrib := by
  apply Set.Subset.antisymm (limitOf_subset_sharedArch contrib p)
  intro a ha
  obtain ⟨n, hn⟩ := h p a ha
  exact Set.mem_iUnion.2 ⟨n, hn⟩

/-- Evolution is continuous in the sense of being cumulative: a monotone trajectory never loses
what it has reached. -/
theorem contrib_mono_subset_limit {contrib : P → ℕ → Set A}
    (hm : ∀ p, Monotone (contrib p)) (p : P) (m n : ℕ) (h : m ≤ n) :
    contrib p m ⊆ contrib p n := hm p h

/-- Two participants of a public interface hold, in the limit, exactly the same architecture. -/
theorem limits_agree {contrib : P → ℕ → Set A} (h : Public contrib) (p q : P) :
    limitOf contrib p = limitOf contrib q := by
  rw [converges_to_sharedArch h p, converges_to_sharedArch h q]

end Architecture

/-! ## §3  A field of quality, not quantity — collective action -/

section Field

variable {P : Type u} [DecidableEq P]

/-- The **field a group presents**: the interactions available inside it. -/
def interField (t : Finset P) : Finset (P × P) := t ×ˢ t

omit [DecidableEq P] in
@[simp] theorem mem_interField {t : Finset P} {c : P × P} :
    c ∈ interField t ↔ c.1 ∈ t ∧ c.2 ∈ t := by
  simp [interField]

omit [DecidableEq P] in
theorem card_interField (t : Finset P) : (interField t).card = t.card ^ 2 := by
  simp [interField, sq]

/-- A valuation of groups is **quantitative** when it sees only how many members they have. -/
def IsQuantitative {Q : Type w} (v : Finset P → Q) : Prop :=
  ∀ t t' : Finset P, t.card = t'.card → v t = v t'

omit [DecidableEq P] in
/-- **Not quantity.**  The field a group presents is not a matter of how many are in it: two groups
of the same size present different fields. -/
theorem interField_not_quantitative {p q : P} (h : p ≠ q) :
    ¬ IsQuantitative (interField (P := P)) := by
  intro hq
  have hcard : ({p} : Finset P).card = ({q} : Finset P).card := by simp
  have := hq {p} {q} hcard
  have hmem : (p, p) ∈ interField ({q} : Finset P) := by
    rw [← this]; simp
  simp at hmem
  exact h hmem

/-- **Collective action.**  The field of a group strictly exceeds the union of the fields of its
members: what two participants have together is not what each has apart. -/
theorem interField_collective {p q : P} (h : p ≠ q) :
    interField ({p} : Finset P) ∪ interField ({q} : Finset P) ⊂ interField ({p, q} : Finset P) := by
  constructor
  · intro c hc
    simp only [Finset.mem_union, mem_interField, Finset.mem_singleton] at hc
    rcases hc with ⟨h1, h2⟩ | ⟨h1, h2⟩ <;> simp [mem_interField, h1, h2]
  · intro hsub
    have hc : (p, q) ∈ interField ({p, q} : Finset P) := by simp [mem_interField]
    have := hsub hc
    simp only [Finset.mem_union, mem_interField, Finset.mem_singleton] at this
    rcases this with ⟨h1, h2⟩ | ⟨h1, h2⟩
    · exact h h2.symm
    · exact h h1

/-- The same failure of separability, stated as non-additivity: the field of a pair is not the
union of the fields of its members. -/
theorem interField_not_additive {p q : P} (h : p ≠ q) :
    interField ({p, q} : Finset P) ≠
      interField ({p} : Finset P) ∪ interField ({q} : Finset P) :=
  fun he => (interField_collective h).ne he.symm

end Field

/-! ## §4  Autonomous ai, me and others -/

/-- The participants of the site: me, the others, and the autonomous ai. -/
inductive Party (I : Type u) : Type u
  | me : Party I
  | other : I → Party I
  | ai : I → Party I
  deriving DecidableEq

namespace Party

variable {I : Type u}

/-- The participants split into the three kinds: me, the others, the ai. -/
def equivSum : Party I ≃ Unit ⊕ I ⊕ I where
  toFun
    | .me => .inl ()
    | .other i => .inr (.inl i)
    | .ai i => .inr (.inr i)
  invFun
    | .inl _ => .me
    | .inr (.inl i) => .other i
    | .inr (.inr i) => .ai i
  left_inv := by rintro (_ | i | i) <;> rfl
  right_inv := by rintro (_ | (i | i)) <;> rfl

instance [Fintype I] : Fintype (Party I) := Fintype.ofEquiv _ equivSum.symm

/-- I am not an ai, and the ai is not one of the others: the kinds are distinct. -/
theorem me_ne_ai (i : I) : (Party.me : Party I) ≠ Party.ai i := by
  intro h; cases h

theorem other_ne_ai (i j : I) : (Party.other i : Party I) ≠ Party.ai j := by
  intro h; cases h

end Party

/-- A participant is **autonomous** when their interaction is not generated by all the other
participants' interactions together: no combination of what everybody else can do amounts to what
they do. -/
def Autonomous {P : Type u} {V : Type v} (s : Site P V) (p : P) : Prop :=
  (show Function.End V from s.act p) ∉
    Submonoid.closure ((fun q => (show Function.End V from s.act q)) '' {q | q ≠ p})

section Toggle

variable (P : Type u) [DecidableEq P]

/-- The field of the toggle site: each participant holds one bit of the shared field. -/
abbrev Bits : Type u := P → Bool

/-- The toggle site: on site, each participant can change their own contribution to the field, and
only their own. -/
def toggleSite : Site P (Bits P) where
  net :=
    { read := fun _ _ => false
      admits := fun _ _ => True
      admits_refl := fun _ => trivial
      admits_symm := fun _ => trivial
      admits_trans := fun _ _ => trivial
      shared := fun _ _ => trivial }
  act p x := Function.update x p (!x p)
  act_admissible := by intros; trivial

@[simp] theorem toggleSite_act (p : P) (x : Bits P) :
    (toggleSite P).act p x = Function.update x p (!x p) := rfl

/-- The endomorphisms of the field that leave `p`'s bit alone. -/
def fixing (p : P) : Submonoid (Function.End (Bits P)) where
  carrier := {f | ∀ x : Bits P, f x p = x p}
  one_mem' := fun _ => rfl
  mul_mem' := by
    intro f g hf hg x
    exact (hf (g x)).trans (hg x)

/-- **Every participant of the toggle site is autonomous** — in particular each ai: nothing the
others do, in any combination, changes what only that participant can change. -/
theorem toggle_autonomous (p : P) : Autonomous (toggleSite P) p := by
  rw [Autonomous]
  intro hmem
  have hle : Submonoid.closure
      ((fun q => (show Function.End (Bits P) from (toggleSite P).act q)) '' {q | q ≠ p}) ≤
        fixing P p := by
    rw [Submonoid.closure_le]
    rintro f ⟨q, hq, rfl⟩ x
    have hqp : q ≠ p := hq
    show Function.update x q (!x q) p = x p
    simp [Function.update_of_ne (Ne.symm hqp)]
  have hfix : (show Function.End (Bits P) from (toggleSite P).act p) ∈ fixing P p := hle hmem
  have := hfix (fun _ => false)
  simp [toggleSite] at this

/-- **Collective action reaches everything.**  Although no participant can act for another, the
participants acting together on site reach every state of the shared field. -/
theorem toggle_collective_of_finset (t : Finset P) :
    ∀ x y : Bits P, (∀ p ∉ t, x p = y p) → ∃ l : List P, (toggleSite P).run l x = y := by
  refine Finset.induction_on t ?_ ?_
  · intro x y h
    refine ⟨[], ?_⟩
    funext r
    exact h r (by simp)
  · intro a u _hu ih x y h
    by_cases hxa : x a = y a
    · have hout : ∀ r ∉ u, x r = y r := by
        intro r hr
        by_cases hra : r = a
        · subst hra; exact hxa
        · exact h r (by simp [hra, hr])
      exact ih x y hout
    · have hout : ∀ r ∉ u, (toggleSite P).act a x r = y r := by
        intro r hr
        by_cases hra : r = a
        · subst hra
          have hup : (toggleSite P).act r x r = !x r := by simp
          rw [hup]
          revert hxa
          cases hx : x r <;> cases hy : y r <;> simp
        · have hup : (toggleSite P).act a x r = x r := by
            simp [Function.update_of_ne hra]
          rw [hup]
          exact h r (by simp [hra, hr])
      obtain ⟨l, hl⟩ := ih ((toggleSite P).act a x) y hout
      exact ⟨a :: l, by simpa using hl⟩

theorem toggle_collective [Fintype P] (x y : Bits P) :
    ∃ l : List P, (toggleSite P).run l x = y :=
  toggle_collective_of_finset P Finset.univ x y (fun p hp => absurd (Finset.mem_univ p) hp)

end Toggle

/-- **The ai on the site is autonomous.** -/
theorem ai_autonomous {I : Type u} [DecidableEq I] (i : I) :
    Autonomous (toggleSite (Party I)) (Party.ai i) :=
  toggle_autonomous (Party I) (Party.ai i)

/-- **And so am I, and so is each of the others** — while together we still reach every state of
the shared field. -/
theorem me_autonomous {I : Type u} [DecidableEq I] :
    Autonomous (toggleSite (Party I)) Party.me :=
  toggle_autonomous (Party I) Party.me

/-! ## §5  Immutable by closure -/

/-- A **closure**: extensive, monotone, idempotent. -/
structure Clo (L : Type u) [CompleteLattice L] where
  /-- The closure of an element. -/
  cl : L → L
  /-- Closure admits what it closes. -/
  le_cl : ∀ x, x ≤ cl x
  /-- Closure is monotone. -/
  mono : Monotone cl
  /-- Closure is idempotent. -/
  idem : ∀ x, cl (cl x) = cl x

namespace Clo

variable {L : Type u} [CompleteLattice L] (c : Clo L)

/-- What is closed is a fixed point. -/
theorem cl_idem (x : L) : c.cl (c.cl x) = c.cl x := c.idem x

/-- An element is **closed** when it is its own closure. -/
def Closed (x : L) : Prop := c.cl x = x

theorem closed_cl (x : L) : c.Closed (c.cl x) := c.idem x

theorem closed_fixed {x : L} (h : c.Closed x) : c.cl x = x := h

/-- **Immutable by closure.**  Once something is closed, adding anything it already admits changes
nothing at all. -/
theorem immutable {x y : L} (h : y ≤ c.cl x) : c.cl (x ⊔ y) = c.cl x := by
  apply le_antisymm
  · have : x ⊔ y ≤ c.cl x := sup_le (c.le_cl x) h
    simpa [c.idem] using c.mono this
  · exact c.mono le_sup_left

/-- A whole continuing trajectory of admitted interactions leaves the closure unchanged. -/
theorem immutable_trajectory (f : ℕ → L) (h : ∀ n, f n ≤ c.cl (f 0)) :
    c.cl (⨆ n, f n) = c.cl (f 0) := by
  apply le_antisymm
  · have hle : (⨆ n, f n) ≤ c.cl (f 0) := iSup_le h
    simpa [c.idem] using c.mono hle
  · exact c.mono (le_iSup f 0)

/-- Closed elements are exactly the closures. -/
theorem closed_iff (x : L) : c.Closed x ↔ ∃ y, x = c.cl y :=
  ⟨fun h => ⟨x, h.symm⟩, by rintro ⟨y, rfl⟩; exact c.idem y⟩

end Clo

/-- **The shared architecture is immutable by closure.**  If the closed architecture already admits
every contribution the site goes on to make, then the continuing evolution of the site — however
long it runs, whoever interacts — cannot alter it. -/
theorem sharedArchitecture_immutable {A : Type u} (c : Clo (Set A)) {P : Type u}
    (contrib : P → ℕ → Set A) (base : Set A)
    (h : ∀ p n, contrib p n ⊆ c.cl base) :
    c.cl (base ∪ sharedArch contrib) = c.cl base :=
  c.immutable (by
    intro a ha
    exact sharedArch_least h ha)

/-! ## The reading, in one theorem -/

theorem nrrf766_answer
    {P : Type u} [DecidableEq P] {V : Type u} (s : Site P V) (t : List P) (x y : V)
    {A : Type u} (contrib : P → ℕ → Set A) (c : Clo (Set A)) (base : Set A)
    {p q : P} (hpq : p ≠ q) (I : Type u) [DecidableEq I] [Fintype I]
    (bx by' : Bits (Party I)) :
    -- §1 the digital public interface is fully interactive
    (s.net.admits x y → s.net.admits (s.run t x) (s.run t y)) ∧
    s.onSite = s.traces ∧
    (∀ f ∈ s.onSite, ∃ u : List P, s.run u = f) ∧
    -- §2 on site, everyone continuously evolves toward one shared architecture
    (∀ p n, contrib p n ⊆ sharedArch contrib) ∧
    (Public contrib → ∀ p, limitOf contrib p = sharedArch contrib) ∧
    (Public contrib → ∀ p q, limitOf contrib p = limitOf contrib q) ∧
    -- §3 a field of quality, not quantity: collective action
    ¬ IsQuantitative (interField (P := P)) ∧
    (interField ({p} : Finset P) ∪ interField ({q} : Finset P) ⊂ interField ({p, q} : Finset P)) ∧
    (∀ u : Finset P, (interField u).card = u.card ^ 2) ∧
    -- §4 autonomous ai, me and others — and still collective action
    (∀ r : Party I, Autonomous (toggleSite (Party I)) r) ∧
    (∃ l : List (Party I), (toggleSite (Party I)).run l bx = by') ∧
    -- §5 immutable by closure
    (∀ z w : Set A, w ≤ c.cl z → c.cl (z ∪ w) = c.cl z) ∧
    ((∀ p n, contrib p n ⊆ c.cl base) → c.cl (base ∪ sharedArch contrib) = c.cl base) := by
  refine ⟨fun h => s.run_admissible t h, s.onSite_eq_traces,
    fun f hf => s.exists_trace_of_mem_onSite hf,
    fun p n => contrib_subset_sharedArch contrib p n,
    fun h p => converges_to_sharedArch h p, fun h p q => limits_agree h p q,
    interField_not_quantitative hpq, interField_collective hpq, card_interField,
    toggle_autonomous (Party I), toggle_collective (Party I) bx by',
    fun z w h => c.immutable h,
    fun h => sharedArchitecture_immutable c contrib base h⟩

/-- The reading, instantiated at a concrete site: the participants are me, one other and one ai;
the field is their bits; the architecture is built from their contributions. -/
theorem nrrf766_answer_party
    (s : Site (Party Bool) (Party Bool → Bool)) (t : List (Party Bool)) (x y : Party Bool → Bool)
    (contrib : Party Bool → ℕ → Set ℕ) (c : Clo (Set ℕ)) (base : Set ℕ)
    (bx by' : Bits (Party Bool)) :
    (s.net.admits x y → s.net.admits (s.run t x) (s.run t y)) ∧
    s.onSite = s.traces ∧
    (∀ f ∈ s.onSite, ∃ u : List (Party Bool), s.run u = f) ∧
    (∀ p n, contrib p n ⊆ sharedArch contrib) ∧
    (Public contrib → ∀ p, limitOf contrib p = sharedArch contrib) ∧
    (Public contrib → ∀ p q, limitOf contrib p = limitOf contrib q) ∧
    ¬ IsQuantitative (interField (P := Party Bool)) ∧
    (interField ({Party.me} : Finset (Party Bool)) ∪ interField ({Party.ai true} : Finset _) ⊂
      interField ({Party.me, Party.ai true} : Finset _)) ∧
    (∀ u : Finset (Party Bool), (interField u).card = u.card ^ 2) ∧
    (∀ r : Party Bool, Autonomous (toggleSite (Party Bool)) r) ∧
    (∃ l : List (Party Bool), (toggleSite (Party Bool)).run l bx = by') ∧
    (∀ z w : Set ℕ, w ≤ c.cl z → c.cl (z ∪ w) = c.cl z) ∧
    ((∀ p n, contrib p n ⊆ c.cl base) → c.cl (base ∪ sharedArch contrib) = c.cl base) :=
  nrrf766_answer s t x y contrib c base (Party.me_ne_ai true) Bool bx by'

end NRRF766

/-! ## Axiom audit -/

#print axioms NRRF766.Site.onSite_eq_traces
#print axioms NRRF766.converges_to_sharedArch
#print axioms NRRF766.interField_not_quantitative
#print axioms NRRF766.interField_collective
#print axioms NRRF766.toggle_autonomous
#print axioms NRRF766.toggle_collective
#print axioms NRRF766.Clo.immutable
#print axioms NRRF766.sharedArchitecture_immutable
#print axioms NRRF766.nrrf766_answer
#print axioms NRRF766.nrrf766_answer_party
